### ISSUE TITLE
tomorrow.io API

### ISSUE THREAD

**Issue by cgmckeever** [ersimont/weather#10]
Sorry for the random ping, but stumbled on your repo while looking for resources on the tomorrow.io API. 
Im trying to understand the API calls and struggling a bit with their docs.

In the evening (ie 11pm) I want to grab the current days total rain accumulation and in the am (ie 2am) I want to grab the potential rain for the day. However, when I run the API call, it returns start times at 9pm `2022-02-18T21:00:00-06:00` so its really confusing what the results are. Any insight into what Im doing wrong would be amazing

```
{
    "location": {
        "type": "Point",
        "coordinates": [
            41.8781,
            87.6298
        ]
    },
    "fields": [
        "temperature",
        "rainIntensity",
        "precipitationProbability",
        "precipitationType"

    ],
    "timesteps": [
        "1d"
    ],
    "timezone": "America/Chicago",
    "startTime": "2022-02-18T02:00:00-06:00",
    "endTime": "2022-02-19T02:00:00-06:00"
}
```

**Comment by ersimont** [comment]
Hello! I'm afraid I'm not sure 😞. I use their "timelines" endpoint and just display the times that are returned, without caring in advance what they will be.

**Comment by cgmckeever** [comment]
Was worth a shot asking !! Thanks ..
